## Data check
```{r}
data <- read.csv("data/data_student.csv")
summary(data)
```
## Tidyverse library
```{r}
library(tidyverse)
```

# Descriptive Statistics
```{r}
data %>% # "tibble" = table of data
  summarise_if(is.numeric, list( #Apply summary functions only if the column is numeric
    mean = mean,
    sd = sd,
    median = median,
    quantile = quantile,
    min = min,
    max = max
  ), na.rm = TRUE) # Ignore missing values
summary(data)
```
# Explain why the summary is different from one column to the next.
> Because on one hand there are text columns (like Name/First Name/City...) and on the other hand, there are "numeric" ones (Weight, Height, YearsIn...). It depends on the column type.

## Weight histogram
```{r}
hist(data$Weight, 
     main = "Weight Histogram", 
     xlab = "Weight",
     col = "orange", 
     border = "black")
```
# Weight densitogram
```{r}
# Plot density (densitogram) for the 'Weight' column
plot(density(data$Weight, na.rm = TRUE),
     main = "Weight Densitogram",
     xlab = "Weight",
     ylab = "Density",
     col = "orange",
     lwd = 2)
```

